name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: EPO
    outputs:
        current-time:
         value: ${{ jobs.reusable-job.outputs.time }}       

jobs:
  reusable-job-1:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greeting
        run: echo "Hi ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
        
  reusable-job-2:
    runs-on: ubuntu-latest
    needs: reusable-job-1
    outputs:
      time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greeting
        run: echo "Hi ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
