name: Secrets and Vars

on: [workflow_dispatch]

jobs:
  display-demo:
    name: Showing secrets and vars
    runs-on: ubuntu-latest
    steps:
      - run: echo "A secret ${{ secrets.MY_REPO_SECRET }}"
      - run: echo "A variable ${{ vars.MY_REPO_VAR }}"
